version: '2'
services:
  db:
    restart: always
    image: mariadb
    user: "1000"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: feast
    volumes:
      - ./tools/mariadb:/var/lib/mysql
  web:
    restart: always
    build: .
    volumes:
      - /code/src/static
    depends_on:
      - db
  nginx:
    restart: always
    build: tools/nginx
    command: /bin/bash -c "nginx"
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
